In [ ]:
import pandas as pd

In [ ]:
def print_df(df):
  print(df.head)

In [ ]:
def print_dims(df):
  print("dimensions", df.shape)

# **Data Cleaning**

Step 1:- Cleaning rows which does not have country as United Kingdom. As the dataset is skewed towards UK(1.4M data entries).

Step 2:- Deleting rows which has empty row values or Nan in a relevent data columns such as Invoice Number, Item Name, Quantity, Transaction Date.

Step 3:- Removing Irrelevent Columns from the dataset such as StockCode, Customer ID, Price, Country.

Step 4:- Clearing space in front and back of the Item Name to remove duplication of data.

In [ ]:
def country(df):
    df.drop(df[df['Country'] != "United Kingdom"].index, inplace = True)
    return df

def emptyrows(df):
    try:
        data = df.dropna(subset=['Invoice', 'Description', 'InvoiceDate'])
    except:
        data = df.dropna(subset=['BillNo', 'Itemname', 'Date'])
    return data

def irrelevent(df):
    try:
        df = df.drop('CustomerID', axis=1)
        df = df.drop('Price', axis=1)
        df = df.drop('Country', axis=1)
    except:
        df = df.drop('StockCode', axis=1)
        df = df.drop('Price', axis=1)
        df = df.drop('Customer ID', axis=1)
        df = df.drop('Country', axis=1)
    return df

In [ ]:
def clean_spaces(df) :
    try :
      df["Itemname"]=df["Itemname"].str.strip()
    except :
      df["Description"]=df["Description"].str.strip()
    return df

In [ ]:
    df1 = pd.read_csv('Dataset1.csv', error_bad_lines=False, sep=';')
    df2 = pd.read_csv('Dataset2.csv', error_bad_lines=False)



    df1 = country(df1)
    df2 = country(df2)

    print("dimensions of dataset 1 after step 1: ")
    print_dims(df1)
    print("dimensions of dataset 2 after step 1: ")
    print_dims(df2)


    df1 = emptyrows(df1)
    df2 = emptyrows(df2)

    print("dimensions of dataset 1 after step 2: ")
    print_dims(df1)
    print("dimensions of dataset 2 after step 2: ")
    print_dims(df2)

    df1 = irrelevent(df1)
    df2 = irrelevent(df2)

    print("dimensions of dataset 1 after step 3: ")
    print_dims(df1)
    print("dimensions of dataset 2 after step 3: ")
    print_dims(df2)

    df1 = clean_spaces(df1)
    df2 = clean_spaces(df2)

    print("dimensions of dataset 1 after step 4: ")
    print_dims(df1)
    print("dimensions of dataset 2 after step 4: ")
    print_dims(df2)
    
    df1.to_csv('dataframe1.csv',index=False)
    df2.to_csv('dataframe2.csv',index=False)

    print("Output of data cleaning")
    print_df(df1)
    print_df(df2)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

dimensions of dataset 1 after step 1:
dimensions (487622, 7)
dimensions of dataset 2 after step 1:
dimensions (963819, 8)
dimensions of dataset 1 after step 2:
dimensions (486167, 7)
dimensions of dataset 2 after step 2:
dimensions (959447, 8)
dimensions of dataset 1 after step 3:
dimensions (486167, 4)
dimensions of dataset 2 after step 3:
dimensions (959447, 4)
dimensions of dataset 1 after step 4:
dimensions (486167, 4)
dimensions of dataset 2 after step 4:
dimensions (959447, 4)
Output of data cleaning
<bound method NDFrame.head of         BillNo                             Itemname  Quantity  \
0       536365   WHITE HANGING HEART T-LIGHT HOLDER         6
1       536365                  WHITE METAL LANTERN         6
2       536365       CREAM CUPID HEARTS COAT HANGER         8
3       536365  KNITTED UNION FLAG HOT WATER BOTTLE         6
4       536365       RED WOOLLY HOTTIE WHITE HEART.         6
...        ...                                  ...       ...
522044  581585       FAIRY TALE COTTAGE NIGHT LIGHT        12
522045  581586  LARGE CAKE STAND  HANGING STRAWBERY         8
522046  581586     SET OF 3 HANGING OWLS OLLIE BEAK        24
522047  581586        RED RETROSPOT ROUND CAKE TINS        24
522048  581586                DOORMAT RED RETROSPOT        10

                    Date
0       01.12.2010 08:26
1       01.12.2010 08:26
2       01.12.2010 08:26
3       01.12.2010 08:26
4       01.12.2010 08:26
...                  ...
522044  09.12.2011 12:31
522045  09.12.2011 12:49
522046  09.12.2011 12:49
522047  09.12.2011 12:49
522048  09.12.2011 12:49

[486167 rows x 4 columns]>
<bound method NDFrame.head of         Invoice                          Description  Quantity  \
0        489434  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1        489434                   PINK CHERRY LIGHTS        12
2        489434                  WHITE CHERRY LIGHTS        12
3        489434          RECORD FRAME 7" SINGLE SIZE        48
4        489434       STRAWBERRY CERAMIC TRINKET BOX        24
...         ...                                  ...       ...
1048570  580501        DOORMAT KEEP CALM AND COME IN         2
1048571  580501         MEMO BOARD RETROSPOT  DESIGN         3
1048572  580502                HEART OF WICKER SMALL         3
1048573  580502                VINTAGE BELLS GARLAND         2
1048574  580502    PAPER LANTERN 9 POINT DELUXE STAR         1

              InvoiceDate
0        01-12-2009 07:45
1        01-12-2009 07:45
2        01-12-2009 07:45
3        01-12-2009 07:45
4        01-12-2009 07:45
...                   ...
1048570  04-12-2011 13:00
1048571  04-12-2011 13:00
1048572  04-12-2011 13:15
1048573  04-12-2011 13:15
1048574  04-12-2011 13:15

[959447 rows x 4 columns]>

# **Data PreProcessing**

Task 1:- Update the header of columns in both dataset to be comman.

Task 2:- Add MD5 Hashcode for item name in each row. Alias for stockcode in both dataset with same hashcode function.

In [ ]:
import hashlib

def update_column_name(dataframe):
    dataframe.rename(columns={'Description': 'Itemname', 'InvoiceDate': 'Date', 'BillNo': 'Invoice'}, inplace=True)

def add_hash(dataframe):
    dataframe['HashCode'] = dataframe['Itemname'].apply(lambda x: hashlib.md5(x.encode()).hexdigest())

def save_output(dataframe, file_name):
    dataframe.to_csv(file_name, index=False)

In [ ]:
df1 = pd.read_csv('dataframe1.csv', error_bad_lines=False)
df2 = pd.read_csv('dataframe2.csv', error_bad_lines=False)

update_column_name(df1)
update_column_name(df2)

add_hash(df1)
add_hash(df2)

save_output(df1, 'data_preprocessing_output1.csv')
save_output(df2, 'data_preprocessing_output2.csv')

# **Data Integration**

Combine the two datasets into a single dataset

In [ ]:
df1 = pd.read_csv('data_preprocessing_output1.csv',  error_bad_lines=False)
df2 = pd.read_csv('data_preprocessing_output2.csv', error_bad_lines=False)
data_integration_frame = pd.concat([df1, df2], axis=0, ignore_index=True)
data_integration_frame.to_csv('data_integration_output.csv', index=False)

In [ ]:
print(data_integration_frame.head)

<bound method NDFrame.head of         Invoice                             Itemname  Quantity  \
0        536365   WHITE HANGING HEART T-LIGHT HOLDER         6
1        536365                  WHITE METAL LANTERN         6
2        536365       CREAM CUPID HEARTS COAT HANGER         8
3        536365  KNITTED UNION FLAG HOT WATER BOTTLE         6
4        536365       RED WOOLLY HOTTIE WHITE HEART.         6
...         ...                                  ...       ...
1445609  580501        DOORMAT KEEP CALM AND COME IN         2
1445610  580501         MEMO BOARD RETROSPOT  DESIGN         3
1445611  580502                HEART OF WICKER SMALL         3
1445612  580502                VINTAGE BELLS GARLAND         2
1445613  580502    PAPER LANTERN 9 POINT DELUXE STAR         1

                     Date                          HashCode
0        01.12.2010 08:26  55847e72942d9171c8e5b818e6914e36
1        01.12.2010 08:26  10356e8f2d4a3cfd5fb2e196de97d914
2        01.12.2010 08:26  eadf42df15e10fa91f37cb89d5ab5169
3        01.12.2010 08:26  c6861275f5db1026fc3caaa782c084d5
4        01.12.2010 08:26  63d60c916043b9fe2ab08d332420ba11
...                   ...                               ...
1445609  04-12-2011 13:00  ca78cb11f5d41e196208aaad1bf318c9
1445610  04-12-2011 13:00  3c8ac0871ac52d6b09ffb80dbd518038
1445611  04-12-2011 13:15  2a58ffee7f85b680b99e5d96337710a5
1445612  04-12-2011 13:15  990a12524818be99b10bb86f9e61722b
1445613  04-12-2011 13:15  f3422a31b3b6b3c17e84055f8ae67225

[1445614 rows x 5 columns]>

# **Data Transformation**

Transform the data into a matrix of 0s and 1s where the rows represent the Invoice and columns represent the HashCode (items)

In [ ]:
dataframe = pd.read_csv('data_integration_output.csv', error_bad_lines=False)

apriori_input_dataset = dataframe.groupby(['Invoice', "HashCode"])['Quantity'].sum().unstack().fillna(0).applymap(lambda x: 1 if x > 0 else 0)
apriori_input_dataset.to_csv('data_transformation_output.csv', index=False)

This provides a reverse mapping between the item and the hash code

In [ ]:
def get_item_from_hash(hash_code):
    item_name = data_integration_frame[dataframe["HashCode"] == hash_code][["Itemname"]].values[0].tolist()
    return item_name

print(get_item_from_hash('55847e72942d9171c8e5b818e6914e36'))

['WHITE HANGING HEART T-LIGHT HOLDER']

# **Apriori Algorithm**

Task 1:- Calculate the frequent itemsets based on apriori algorithm and minimum support of 0.01

Task 2:- Sort the results based on support in descending order

In [ ]:
from mlxtend.frequent_patterns import apriori, association_rules
frequent_itemsets = apriori(apriori_input_dataset, min_support=0.01, use_colnames=True)
frequent_itemsets.sort_values("support", ascending=False).head(20)

      support                            itemsets
205  0.120848  (55847e72942d9171c8e5b818e6914e36)
96   0.082576  (29e30bee90acbea2857f2ef787fe19f5)
384  0.076074  (ac3c46aa4f4822c13368734916814169)
232  0.066484  (63807ffdeb30706f370000821bfc8516)
159  0.062095  (4154e42792974c791a153945bade7377)
127  0.053281  (32eae5f073828207e230b432f0c8f175)
466  0.053100  (d16ac30e35cc2cbf02145487b15eeee7)
99   0.051276  (2a58ffee7f85b680b99e5d96337710a5)
309  0.050824  (8e2a7f29acc72e5365ac27eca251d9af)
56   0.050012  (1851ced19231c9e37b5036ab0d143ab2)
67   0.047826  (1c3ba7b45b8d8f4fc43b0b44f16e644f)
380  0.047519  (aaea8967f52bffc6a93a6154216365b1)
118  0.045641  (3032b93a47a6e5da15a0290417f91f50)
61   0.045370  (19a471f853f2b5bf35ffe94e1fb002a9)
53   0.045352  (179c78e9e65fcff8e5cfeac52c84b9de)
474  0.045135  (d5000e15cd5ef6b8cfe51ac792831712)
39   0.044846  (11d6a23ea24698b53e5a464967547031)
472  0.044720  (d3de0337287d355664d3b3bb69261a8b)
115  0.043961  (2f89e841ec4593407f026dc7e034edf1)
262  0.043925  (7035c67c9ef698ef4490fbea5375039e)

# **Association rules**

Identify the association rules and sort the results based on confidence

In [ ]:
rules = association_rules(frequent_itemsets, metric="support", min_threshold=0.01)
rules.sort_values("confidence", ascending=False).head(30)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
549,"(c9bb4e5985258ac4ef5d96bf5447659b, 3ce0b157826...",(1f23d9ea2d5e063594e69921455eceb7),0.019308,0.033540,0.017519,0.907390,27.054102,0.016872,10.435817
542,"(c9bb4e5985258ac4ef5d96bf5447659b, 29e30bee90a...",(1f23d9ea2d5e063594e69921455eceb7),0.012643,0.033540,0.011216,0.887143,26.450425,0.010792,8.563571
548,"(c9bb4e5985258ac4ef5d96bf5447659b, 1f23d9ea2d5...",(3ce0b15782688e4cbdaecc5135596259),0.020445,0.034226,0.017519,0.856890,25.036124,0.016820,6.748494
554,"(c9bb4e5985258ac4ef5d96bf5447659b, 29e30bee90a...",(3ce0b15782688e4cbdaecc5135596259),0.012643,0.034226,0.010674,0.844286,24.667845,0.010242,6.202217
88,(c9bb4e5985258ac4ef5d96bf5447659b),(1f23d9ea2d5e063594e69921455eceb7),0.024708,0.033540,0.020445,0.827485,24.671719,0.019617,5.602193
525,"(c05f3ec0e4eface25a6fdfc90061ad69, 18f67b2097b...",(a7e5c3a46763d98594a5e281c04ce646),0.012498,0.029133,0.010169,0.813584,27.926655,0.009804,5.208062
585,"(2fd83514280901cae3cfd0bef64f2551, 8e2a7f29acc...",(ac3c46aa4f4822c13368734916814169),0.015045,0.076074,0.012083,0.803121,10.557078,0.010938,4.692867
536,"(29e30bee90acbea2857f2ef787fe19f5, 3ce0b157826...",(1f23d9ea2d5e063594e69921455eceb7),0.017122,0.033540,0.013546,0.791139,23.588049,0.012972,4.627294
578,"(8969f2d72252cdace9d45d3bc3642647, 2fd83514280...",(ac3c46aa4f4822c13368734916814169),0.013438,0.076074,0.010620,0.790323,10.388839,0.009598,4.406415
573,"(2fd83514280901cae3cfd0bef64f2551, 32eae5f0738...",(ac3c46aa4f4822c13368734916814169),0.016689,0.076074,0.013185,0.790043,10.385168,0.011915,4.400554
537,"(29e30bee90acbea2857f2ef787fe19f5, 1f23d9ea2d5...",(3ce0b15782688e4cbdaecc5135596259),0.017158,0.034226,0.013546,0.789474,23.066380,0.012959,4.587426
592,"(2fd83514280901cae3cfd0bef64f2551, 8eaccf2f548...",(ac3c46aa4f4822c13368734916814169),0.012715,0.076074,0.010024,0.788352,10.362939,0.009057,4.365394
244,(c9bb4e5985258ac4ef5d96bf5447659b),(3ce0b15782688e4cbdaecc5135596259),0.024708,0.034226,0.019308,0.781433,22.831444,0.018462,4.418658
378,(6e2338527902f0d939f20ad976a99e5d),(6d030e9ce4022792ae41baf95050946e),0.015099,0.015786,0.011686,0.773923,49.027253,0.011447,4.353456
397,(bdbe1af2f98d65d78fdd6541143e7e98),(85c82ac87b14588d664996b6d277d50d),0.016237,0.019904,0.012444,0.766407,38.506046,0.012121,4.195746
84,(1f23d9ea2d5e063594e69921455eceb7),(3ce0b15782688e4cbdaecc5135596259),0.033540,0.034226,0.025304,0.754443,22.042863,0.024156,3.932987
277,(b5d37726eb76e3280471556f8b449b8a),(4b169ef4d4d6d1eabbea83857d19c2c0),0.015424,0.018260,0.011613,0.752927,41.233760,0.011332,3.973488
483,(b532fc10e45073b96e0cddae37cf7d67),(af5cf90cb94acab45dcc031a338c4a00),0.020608,0.033973,0.015316,0.743208,21.876226,0.014616,3.761899
379,(6d030e9ce4022792ae41baf95050946e),(6e2338527902f0d939f20ad976a99e5d),0.015786,0.015099,0.011686,0.740275,49.027253,0.011447,3.792085
85,(3ce0b15782688e4cbdaecc5135596259),(1f23d9ea2d5e063594e69921455eceb7),0.034226,0.033540,0.025304,0.739314,22.042863,0.024156,3.707372
670,"(db5ed5538b6bb295e0a755f209f95e6f, a7e5c3a4676...",(c05f3ec0e4eface25a6fdfc90061ad69),0.013618,0.031698,0.010024,0.736074,23.221780,0.009592,3.668844
262,(418088c652a8d028ed552171e5dda7f8),(af5cf90cb94acab45dcc031a338c4a00),0.015442,0.033973,0.011361,0.735673,21.654429,0.010836,3.654659
439,(c3c7cf2165de919dc89d28c364873983),(9172c159af10f2a9a501b9f1dec3b2f5),0.018350,0.021999,0.013420,0.731299,33.242893,0.013016,3.639741
614,"(8eaccf2f548ab061a93c6f7e09abfdf3, 8e2a7f29acc...",(32eae5f073828207e230b432f0c8f175),0.013853,0.053281,0.010006,0.722295,13.556369,0.009268,3.409078
307,(603748e5273fa1f3e86ba950b7e46900),(55847e72942d9171c8e5b818e6914e36),0.015749,0.120848,0.011216,0.712156,5.892982,0.009313,3.054265
551,(c9bb4e5985258ac4ef5d96bf5447659b),"(1f23d9ea2d5e063594e69921455eceb7, 3ce0b157826...",0.024708,0.025304,0.017519,0.709064,28.021959,0.016894,3.350212
258,(a1a5b810860af49af101a28f8c50dfa2),(4154e42792974c791a153945bade7377),0.016327,0.062095,0.011541,0.706858,11.383545,0.010527,3.199496
61,(18f67b2097b56360722af9a2b1628016),(a7e5c3a46763d98594a5e281c04ce646),0.021926,0.029133,0.015479,0.705931,24.231414,0.014840,3.301492
639,"(c05f3ec0e4eface25a6fdfc90061ad69, 36bb9dc9070...",(a7e5c3a46763d98594a5e281c04ce646),0.014503,0.029133,0.010205,0.703611,24.151801,0.009782,3.275657
640,"(a7e5c3a46763d98594a5e281c04ce646, 36bb9dc9070...",(c05f3ec0e4eface25a6fdfc90061ad69),0.014557,0.031698,0.010205,0.700993,22.115017,0.009743,3.238389

# **Product Recommendation**

In [ ]:
def recommender(association, hashcode, no_of_products=1):
    association_sorted = association.sort_values("lift", ascending=False)
    rec_list = []

    for i, product in association_sorted["antecedents"].items():
        for j in list(product):
            if j == hashcode:
                rec_list.append(list(association_sorted.iloc[i]["consequents"]))

    rec_list = list({item for item_list in rec_list for item in item_list})

    return rec_list[:no_of_products]

In [ ]:
recommender(rules, "29e30bee90acbea2857f2ef787fe19f5", 4)

['19a471f853f2b5bf35ffe94e1fb002a9',
 'a7e5c3a46763d98594a5e281c04ce646',
 '73ec5ee29ed61eb93ec34f5b530a90ae',
 'd5000e15cd5ef6b8cfe51ac792831712']

In [ ]:
l=["29e30bee90acbea2857f2ef787fe19f5"]

In [ ]:
[[get_item_from_hash(i) for i in recommender(rules, hash, 3)] for hash in l]

[[['WOODEN FRAME ANTIQUE WHITE'],
  ['RED RETROSPOT CHARLOTTE BAG'],
  ['VINTAGE SNAP CARDS']]]